### ISSUE TITLE
JSON and parsing

### ISSUE THREAD

**Issue by blacktm** [blue-button/bluebutton.js#71]
- [ ] Add consistent representation of codes and translations. See #12 and #15
- [ ] Handle all types of `nullFlavor`s
- [ ] Look for multiple "templateIDs" in each CCDA section. See #48
- [ ] Should missing data be `null` or just empty strings ("")? See #62
- [ ] Encounter indication shouldn't be called "finding." See #13
